"""add persistent simulation runs

Revision ID: 5853d211e911
Revises: a49bf5d46046
Create Date: 2026-08-22 19:10:07.752913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5853d211e911'
down_revision: Union[str, Sequence[str], None] = 'a49bf5d46046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Float(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_run_interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=False),
    sa.Column('intervention_name', sa.String(length=100), nullable=False),
    sa.Column('started_day', sa.Integer(), nullable=False),
    sa.Column('evaluation_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_run_interventions')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
