"""SM add customer simulation profiles

Revision ID: 69b3d57d6fa9
Revises: b503bfb655ad
Create Date: 2026-08-17 01:33:25.439725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b3d57d6fa9'
down_revision: Union[str, Sequence[str], None] = 'b503bfb655ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
