"""ProductEvent column name mistake correct

Revision ID: b2f120346b29
Revises: 8736a05db31d
Create Date: 2026-08-16 02:24:11.971770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f120346b29'
down_revision: Union[str, Sequence[str], None] = '8736a05db31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_events', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('product_events', 'occured_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_events', sa.Column('occured_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('product_events', 'occurred_at')
    # ### end Alembic commands ###
