"""add customer simulation profiles

Revision ID: b503bfb655ad
Revises: 4f74410d8d05
Create Date: 2026-08-17 01:27:41.350813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b503bfb655ad'
down_revision: Union[str, Sequence[str], None] = '4f74410d8d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_simulation_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('integration_difficulty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_simulation_profiles')
    # ### end Alembic commands ###
