"""scope customers to simulation runs

Revision ID: b90ec221c694
Revises: 98c6e1871131
Create Date: 2026-08-24 23:26:41.404542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90ec221c694'
down_revision: Union[str, Sequence[str], None] = '98c6e1871131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('simulation_run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'simulation_runs', ['simulation_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'simulation_run_id')
    # ### end Alembic commands ###
