"""separate customer and user events removed product_event

Revision ID: bd76f193a88f
Revises: aa7ae26f9f91
Create Date: 2026-08-16 14:19:45.128642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd76f193a88f'
down_revision: Union[str, Sequence[str], None] = 'aa7ae26f9f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('product_events_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_events_pkey'))
    )
    # ### end Alembic commands ###
